[project]
name = "mapo-social"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "tabulate>=0.9.0",
    "xaibo[local,openai,webserver]>=0.1.6",
]
