[project]
name = "mapo-social"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "xaibo[openai,webserver,local]>=0.1.3",
]
